# Generated by Django 3.2.3 on 2021-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=40)),
                ('location', models.TextField()),
                ('image', models.ImageField(upload_to='poto')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
