# Generated by Django 3.2.3 on 2021-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationmodel',
            name='judul',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='classificationmodel',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
